
input_text = '''The apple doesn't fall. ...
All that glitters are not gold. ...
A picture is worth a thousand words. ...
Beggers can't be choosers. ...
A bird in the hand. ...
Better safe than sorry. ...
An apple a day keeps doctor away. ...
Blood is thicker than water. ...'''


lines = input_text.split('\n')


num_lines = len(lines)
num_sentences_with_b = sum(1 for line in lines if line.strip().startswith('B'))


print(f'Total number of lines: {num_lines}')
print(f'Number of Sentences that start with letter B: {num_sentences_with_b}')
